### ISSUE TITLE
Wrong timestamp created by automation for new releases

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-sandbox/artifacthub#29]
Right now dynatrace-service version 0.18.0 shows up with this on our integrations page https://keptn.sh/docs/integrations

![image](https://user-images.githubusercontent.com/56065213/141142894-1bf92adc-e812-4ee1-ad5e-f3d607435e44.png)

Looking at the yaml file, the date is wrong (note: today is the 10th):
https://github.com/keptn-sandbox/artifacthub/blob/0e831264e1d4ba6aa37a5e1875f7e679d9713352/dynatrace/0.18.0/artifacthub-pkg.yml#L8
https://github.com/keptn-sandbox/artifacthub/blob/0e831264e1d4ba6aa37a5e1875f7e679d9713352/dynatrace/0.18.0/artifacthub-pkg.yml#L4

**Comment by TannerGilbert** [comment]
There is an error with the `DATETIME_FORMAT`

https://github.com/keptn-sandbox/artifacthub/blob/0e831264e1d4ba6aa37a5e1875f7e679d9713352/utils.py#L6

it should be `DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%SZ'` instead.
